[deploy]
#healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
SPRING_PROFILES_ACTIVE = "railway"
PORT = "8080"
JAVA_OPTS = "-Xmx512m -Xms256m"